### ISSUE TITLE
Sectioned form component should open to tabs list on mobile screen

### ISSUE THREAD

**Issue by Blackbaud-Robfavre** [blackbaud/skyux-tabs#36]
### Expected behavior
When opening a sectioned form on a mobile-sized screen, the user should start on the list of tabs.

### Actual behavior
Sectioned form opens on the first tab and user has to navigate back to the list of tabs to select the one they are looking for.

### Steps to reproduce
Open a sectioned form on a mobile sized screen.

### Severity
Medium
### Impact
Medium

[AB#1563968](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1563968)

**Comment by Blackbaud-AlexKingman** [comment]
We're also looking into this same issue for vertical tabs.

**Comment by Blackbaud-IanThomas** [comment]
@Blackbaud-AlexKingman or @Blackbaud-SteveBrush, this looks like nothing more than a change of default behavior.  Is there any barrier to changing this?

I see the default behavior on this line, so it looks like a simple fix. Am I understanding this correctly?
https://github.com/blackbaud/skyux-tabs/blob/master/src/app/public/modules/sectioned-form/sectioned-form.component.ts#L105

**Comment by Blackbaud-DanMiller** [comment]
@Blackbaud-ToddRoberts thoughts on this pattern?

**Comment by Blackbaud-ToddRoberts** [comment]
The intent with loading with the first tab or section is that the majority of the time that's where the user would go, so rather than having to see the tabs then click into the first one we accelerate what they are trying to do. What cases are you running into where the first tab/section is not what the user wants? Or is there some other issue (discoverability of other tabs)?

**Comment by Blackbaud-IanThomas** [comment]
@Blackbaud-ToddRoberts The design of our modal that uses this sectioned form is editing a number of pieces of data on a user that all have equal weight. For example, for a catholic church, the list contains all of their "sacraments", and users will launch this form to modify their sacraments data. There is no strong tendency for a user to edit any particular sacrament first, so we want to load to the tabs view up front so the user doesn't have to go back to the tabs list the majority of the time.

If the right default use case is defaulting to the first tab or section because a user is performing a series of actions in order, perhaps we could make this more flexible by adding a config to override the default?  Currently, we are doing some in-app code to manually show the tabs after the form has loaded.

Here's an example of the modal with 5 different steps, where the relevant one might be different for any given constituent:
![image](https://user-images.githubusercontent.com/5880556/91742885-f5301180-eb84-11ea-9aa3-6da0ece19ca8.png)

**Comment by Blackbaud-ToddRoberts** [comment]
Ok, makes sense. I can see adding an option to open to the form or the tab list.

**Comment by Blackbaud-DanMiller** [comment]
@Blackbaud-IanThomas would you have the time to contribute this change? The SKY UX team won't be able to get to it in the near term.

**Comment by Blackbaud-IanThomas** [comment]
@Blackbaud-DanMiller I was just talking with my team about that. We would like to make the contribution. We are functional right now without workaround, but we will get this on our backlog to get done sometime in the coming weeks.

**Comment by Blackbaud-DanMiller** [comment]
Thanks!

Friendly reminder of the contribution process: https://developer.blackbaud.com/skyux/contribute/contribution-process
