### ISSUE TITLE
Tabs start collapsed

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-tabs#41]
In some scenarios the tabs are started in the collapsed state.  I haven't investigated enough to learn what the requirements to see the bug are; however, you can see it on our tab documentation.

- Visit https://developer.blackbaud.com/skyux/components/tabs
- Click the "Development" tab and scroll down to the "Demo" section.
- Notice the tabs are collapsed.
- Resize the window.
- Notice the tabs are no longer collapsed.

Originally noticed by @Blackbaud-ChristiSchneider.

**Comment by Blackbaud-ChristiSchneider** [comment]
Thanks! I want to reinforce the impact level because I do think this is a fairly bad UX issue - we already had someone who didn't notice that there was a collapsed tab and asked for help finding the thing in the tab, and the site that is seeing this issue has only been up for 4 days and has a pretty small set of internal users.
